# -------------------------------------------------------------------
# CodeBuild Spec
# -------------------------------------------------------------------

version: 0.2


# -------------------------------------------------------------------
# Environment Variables
# -------------------------------------------------------------------

# env:
#   variables:
#     - FOO: bar


# -------------------------------------------------------------------
# Build Phases
# -------------------------------------------------------------------

phases:

  install:
    commands:
      - npm install --global npm@5.0.3
      - npm install --global npx

  # pre_build:
  #   commands:
  #    - aws ssm get-parameters --names "npmrc" --with-decryption > .npmrc

  build:
    commands:
      - npm install
      - npx lenticular generate


# -------------------------------------------------------------------
# Artifacts for S3
# -------------------------------------------------------------------

artifacts:
  base-directory: artifacts
  files:
    - '**/*'
